name: Push Docker Image

on:
    workflow_dispatch:

jobs:
    
    build-and-test:
        uses: ./.github/workflows/docker-image.yml

    
    push:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:

        - uses: actions/checkout@v5
        
        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v4
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Push Docker image to GitHub Container Registry
          run: |
            docker push ghcr.io/dietwall/arm_gcc_image:latest