name: Docker Image CI

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Environment
      run: ./setup_env.sh


    - name: Build Docker image
      run: |
        source venv/bin/activate && ython3 container_operations.py -o build --uid 1000 --gid 1000 --user developer
