name: build and test Docker image
on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

jobs:

  build:
    permissions: write-all    #publish test results
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Environment
      run: ./setup_env.sh

    - name: Build Docker image
      run: |
        source venv/bin/activate && python3 container_operations.py -o build --uid 1000 --gid 1000 --user developer
    
    - name: Run Docker container and test
      run: |
        source venv/bin/activate && python3 container_operations.py -o run test
    
    - name: publish test_results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: (!cancelled())
      with:
        files: |
          test_results*.xml
    
    - name: Save Docker image to tar
      run: |
        #docker save ghcr.io/dietwall/arm_gcc_image:latest > arm_gcc_image.tar
        source venv/bin/activate && python3 container_operations.py -o save --tag ghcr.io/dietwall/arm_gcc_image

    - name: Temporarily save Docker image
      uses: actions/upload-artifact@v7
      with:
        name: arm_gcc_image
        path: arm_gcc_image.tar
        retention-days: 1
